# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, verbose_name='reference')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('first_name', models.CharField(max_length=50, verbose_name='')),
                ('last_name', models.CharField(max_length=50, verbose_name='')),
                ('siret', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50, verbose_name='reference')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
                ('qty', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('first_name', models.CharField(max_length=50, verbose_name='')),
                ('last_name', models.CharField(max_length=50, verbose_name='')),
                ('siret', models.IntegerField(max_length=14, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.User'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.Customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.User'),
        ),
    ]
