# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_auto_20170622_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='date',
        ),
        migrations.AddField(
            model_name='customer',
            name='address_1',
            field=models.CharField(max_length=30, null=True, verbose_name='address 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_2',
            field=models.CharField(max_length=30, null=True, verbose_name='address 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=10, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='zipcode'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='refusal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_1',
            field=models.CharField(max_length=30, null=True, verbose_name='address 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_2',
            field=models.CharField(max_length=30, null=True, verbose_name='address 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=10, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='zipcode'),
        ),
    ]
