# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturation', '0003_auto_20170622_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('siret', models.IntegerField(max_length=14, verbose_name='')),
                ('phone', models.IntegerField(max_length=10, null=True, verbose_name='phone')),
                ('mail', models.CharField(max_length=20, null=True)),
                ('address_1', models.CharField(max_length=30, null=True, verbose_name='address 1')),
                ('address_2', models.CharField(max_length=30, null=True, verbose_name='address 2')),
                ('zip_code', models.IntegerField(null=True, verbose_name='zipcode')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='city')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='country')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.AppUser'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.AppUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
