# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_auto_20170622_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='mail',
            field=models.CharField(max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(max_length=30, null=True, verbose_name='Email'),
        ),
    ]
