# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_auto_20170622_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True, verbose_name='reference')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('refusal_date', models.DateTimeField(blank=True, null=True)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.AppUser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.Status'),
        ),
    ]
